name: amazon
python: 3.7
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - arrow-cpp=0.13.0
  - asn1crypto=1.2.0
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - boost-cpp=1.67.0
  - brotli=1.0.7
  - bzip2=1.0.8
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - cryptography=2.8
  - cudatoolkit=10.0.130
  - cudnn=7.6.4
  - cymem=2.0.2
  - cytoolz=0.9.0.1
  - dbus=1.13.12
  - decorator=4.4.1
  - defusedxml=0.6.0
  - deprecated=1.2.6
  - dill=0.2.9
  - double-conversion=3.1.5
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gflags=2.2.2
  - glib=2.63.1
  - glog=0.4.0
  - gmp=6.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=2.8
  - importlib_metadata=1.3.0
  - intel-openmp=2019.4
  - ipykernel=5.1.3
  - ipython=7.10.2
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.1
  - jinja2=2.10.3
  - joblib=0.14.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_core=4.6.1
  - libboost=1.67.0
  - libedit=3.1.20181209
  - libevent=2.1.8
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libprotobuf=3.6.0
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - lime=0.1.1.36
  - lz4-c=1.8.1.2
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=8.0.2
  - msgpack-numpy=0.4.3.2
  - msgpack-python=0.6.1
  - murmurhash=1.0.2
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - ncurses=6.1
  - networkx=2.3
  - ninja=1.9.0
  - notebook=6.0.2
  - numpy=1.17.4
  - numpy-base=1.17.4
  - openssl=1.1.1d
  - pandas=0.25.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.2
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.3.1
  - plac=0.9.6
  - preshed=2.0.1
  - prometheus_client=0.7.1
  - ptyprocess=0.6.0
  - pyarrow=0.13.0
  - pycparser=2.19
  - pygithub=1.43.6
  - pygments=2.5.2
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyqt=5.9.2
  - pyrsistent=0.15.6
  - pysocks=1.7.1
  - python=3.7.4
  - python-dateutil=2.8.1
  - pytorch=1.1.0
  - pytz=2019.3
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtconsole=4.6.0
  - re2=2019.08.01
  - readline=7.0
  - requests=2.22.0
  - scikit-learn=0.21.3
  - scipy=1.3.2
  - send2trash=1.5.0
  - setuptools=42.0.2
  - sip=4.19.8
  - six=1.13.0
  - snappy=1.1.7
  - snorkel=0.9.3
  - spacy=2.0.16
  - sqlite=3.30.1
  - tensorboardx=1.9
  - terminado=0.8.3
  - testpath=0.4.4
  - thinc=6.12.1
  - thrift-cpp=0.11.0
  - tk=8.6.8
  - toolz=0.10.0
  - tornado=6.0.3
  - tqdm=4.40.2
  - traitlets=4.3.3
  - ujson=1.35
  - urllib3=1.25.7
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - wrapt=1.10.11
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - cycler==0.10.0
    - en-core-web-lg==2.0.0
    - imageio==2.6.1
    - jupyter-console==6.1.0
    - kiwisolver==1.1.0
    - matplotlib==3.1.3
    - munkres==1.1.2
    - nbstripout==0.3.6
    - pillow==7.0.0
    - prompt-toolkit==3.0.3
    - protobuf==3.11.3
    - pyparsing==2.4.6
    - pywavelets==1.1.1
    - regex==2018.1.10
    - scikit-image==0.16.2

