name: amazon
python: 3.7
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - arrow-cpp=0.15.1
  - asn1crypto=1.3.0
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - boost-cpp=1.71.0
  - brotli=1.0.7
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=2.8
  - cudatoolkit=10.0.130
  - cudnn=7.6.5
  - cymem=2.0.2
  - cytoolz=0.9.0.1
  - dbus=1.13.12
  - decorator=4.4.1
  - defusedxml=0.6.0
  - dill=0.2.9
  - double-conversion=3.1.5
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gflags=2.2.2
  - glib=2.63.1
  - glog=0.4.0
  - gmp=6.1.2
  - grpc-cpp=1.26.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=2.8
  - importlib_metadata=1.5.0
  - intel-openmp=2020.0
  - ipykernel=5.1.4
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.16.0
  - jinja2=2.11.1
  - joblib=0.14.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.1.0
  - jupyter_core=4.6.1
  - ld_impl_linux-64=2.33.1
  - libboost=1.71.0
  - libedit=3.1.20181209
  - libevent=2.1.8
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libprotobuf=3.11.2
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - lz4-c=1.8.1.2
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - msgpack-numpy=0.4.3.2
  - msgpack-python=0.6.1
  - munkres=1.0.12
  - murmurhash=1.0.2
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.1
  - networkx=2.3
  - ninja=1.9.0
  - notebook=6.0.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1d
  - pandas=0.25.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.6.1
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - plac=0.9.6
  - preshed=2.0.1
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.3
  - protobuf=3.11.2
  - ptyprocess=0.6.0
  - pyarrow=0.15.1
  - pycparser=2.19
  - pygments=2.5.2
  - pyopenssl=19.1.0
  - pyqt=5.9.2
  - pyrsistent=0.15.7
  - pysocks=1.7.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - pytorch=1.1.0
  - pytz=2019.3
  - pyzmq=18.1.1
  - qt=5.9.7
  - qtconsole=4.6.0
  - re2=2019.08.01
  - readline=7.0
  - regex=2019.12.9
  - requests=2.22.0
  - scikit-learn=0.21.3
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=45.2.0
  - sip=4.19.8
  - six=1.14.0
  - snappy=1.1.7
  - snorkel=0.9.3
  - spacy=2.0.16
  - sqlite=3.31.1
  - tensorboardx=1.9
  - terminado=0.8.3
  - testpath=0.4.4
  - thinc=6.12.1
  - thrift-cpp=0.11.0
  - tk=8.6.8
  - toolz=0.10.0
  - tornado=6.0.3
  - tqdm=4.42.1
  - traitlets=4.3.3
  - ujson=1.35
  - uriparser=0.9.3
  - urllib3=1.25.8
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - wrapt=1.10.11
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=2.2.0
  - zlib=1.2.11
  - zstd=1.3.7

